_BASE_: "./newsrc_acdc_ctcr_lambda1.yaml"

SOLVER:
  CTCMT_CONFLICT_MODE: "aux_head_only"
  CTCMT_ROUTE_SCOPE: "shared"
  CTCMT_AUX_TRUNK_LAMBDA: 1.0

  CTCMT_ADAPTIVE_ROUTING: True
  CTCMT_ADAPTIVE_ROUTING_BETA: 0.98
  CTCMT_ADAPTIVE_ROUTING_EMA: 0.99

  CTCMT_GRAD_DIAG: False
